/* The following code was generated by JFlex 1.6.0 */

package compiladores;
import static compiladores.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>E:/Universidad/Cuarto Año/Compiladores/Compiladores/src/compiladores/Lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\6\1\51\1\51\1\3\22\0\1\3\1\13\3\0"+
    "\1\12\1\24\1\0\1\14\1\15\1\5\1\25\1\0\1\26\1\0"+
    "\1\4\12\2\1\0\1\16\1\7\1\11\1\10\2\0\32\1\1\17"+
    "\1\0\1\20\1\0\1\1\1\0\1\33\1\27\1\37\1\46\1\32"+
    "\1\44\1\1\1\50\1\42\1\1\1\36\1\31\1\1\1\34\1\30"+
    "\2\1\1\35\1\40\1\41\1\43\1\45\1\47\3\1\1\21\1\23"+
    "\1\22\7\0\1\51\u1fa2\0\1\51\1\51\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\1\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\2\1\23\1\24\11\3\1\4"+
    "\1\0\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\10\3\1\35\5\3\1\0\7\3\1\36\1\37"+
    "\6\3\1\40\3\3\1\41\2\3\1\42\2\3\1\43"+
    "\2\3\1\44\1\45\1\46\1\47\1\3\1\50\1\3"+
    "\1\51\1\3\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\52\0\250\0\52\0\322"+
    "\0\374\0\u0126\0\52\0\u0150\0\52\0\52\0\52\0\52"+
    "\0\52\0\52\0\52\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222"+
    "\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372"+
    "\0\u039c\0\u03c6\0\52\0\52\0\52\0\52\0\52\0\52"+
    "\0\52\0\52\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2"+
    "\0\u04ec\0\u0516\0\124\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8"+
    "\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4\0\u070e\0\u0738"+
    "\0\124\0\124\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0834"+
    "\0\124\0\u085e\0\u0888\0\u08b2\0\124\0\u08dc\0\u0906\0\124"+
    "\0\u0930\0\u095a\0\124\0\u0984\0\u09ae\0\124\0\124\0\124"+
    "\0\124\0\u09d8\0\124\0\u0a02\0\124\0\u0a2c\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\5\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\2\3\1\31\2\3\1\32\1\3\1\33\1\3\1\34"+
    "\1\35\1\3\1\36\1\37\1\3\1\40\1\3\54\0"+
    "\2\3\24\0\22\3\3\0\1\4\53\0\1\41\1\42"+
    "\55\0\1\43\51\0\1\44\51\0\1\45\51\0\1\46"+
    "\63\0\1\47\52\0\1\50\36\0\1\51\42\0\1\4"+
    "\6\0\1\52\41\0\2\3\24\0\1\3\1\53\4\3"+
    "\1\54\13\3\2\0\2\3\24\0\2\3\1\55\17\3"+
    "\2\0\2\3\24\0\3\3\1\56\16\3\2\0\2\3"+
    "\24\0\1\3\1\57\1\60\17\3\2\0\2\3\24\0"+
    "\6\3\1\61\13\3\2\0\2\3\24\0\5\3\1\62"+
    "\7\3\1\63\4\3\2\0\2\3\24\0\1\3\1\64"+
    "\1\65\1\3\1\66\15\3\2\0\2\3\24\0\1\3"+
    "\1\67\20\3\2\0\2\3\24\0\21\3\1\70\1\0"+
    "\6\41\1\0\43\41\4\42\1\0\1\71\44\42\1\0"+
    "\2\3\24\0\1\3\1\72\20\3\2\0\2\3\24\0"+
    "\3\3\1\73\16\3\2\0\2\3\24\0\11\3\1\74"+
    "\10\3\2\0\2\3\24\0\12\3\1\75\7\3\2\0"+
    "\2\3\24\0\5\3\1\76\14\3\2\0\2\3\24\0"+
    "\4\3\1\77\15\3\2\0\2\3\24\0\14\3\1\100"+
    "\5\3\2\0\2\3\24\0\12\3\1\101\7\3\2\0"+
    "\2\3\24\0\6\3\1\102\13\3\2\0\2\3\24\0"+
    "\1\3\1\103\20\3\2\0\2\3\24\0\2\3\1\104"+
    "\17\3\2\0\2\3\24\0\13\3\1\105\6\3\2\0"+
    "\2\3\24\0\13\3\1\106\6\3\5\0\1\5\46\0"+
    "\2\3\24\0\2\3\1\107\17\3\2\0\2\3\24\0"+
    "\4\3\1\110\15\3\2\0\2\3\24\0\3\3\1\111"+
    "\16\3\2\0\2\3\24\0\14\3\1\112\5\3\2\0"+
    "\2\3\24\0\12\3\1\113\7\3\2\0\2\3\24\0"+
    "\11\3\1\114\10\3\2\0\2\3\24\0\3\3\1\115"+
    "\16\3\2\0\2\3\24\0\4\3\1\116\15\3\2\0"+
    "\2\3\24\0\11\3\1\117\10\3\2\0\2\3\24\0"+
    "\17\3\1\120\2\3\2\0\2\3\24\0\2\3\1\121"+
    "\17\3\2\0\2\3\24\0\3\3\1\122\16\3\2\0"+
    "\2\3\24\0\7\3\1\123\12\3\2\0\2\3\24\0"+
    "\6\3\1\124\13\3\2\0\2\3\24\0\13\3\1\125"+
    "\6\3\2\0\2\3\24\0\11\3\1\126\10\3\2\0"+
    "\2\3\24\0\12\3\1\127\7\3\2\0\2\3\24\0"+
    "\3\3\1\130\16\3\2\0\2\3\24\0\3\3\1\131"+
    "\16\3\2\0\2\3\24\0\4\3\1\132\15\3\2\0"+
    "\2\3\24\0\5\3\1\133\14\3\2\0\2\3\24\0"+
    "\5\3\1\134\14\3\2\0\2\3\24\0\5\3\1\135"+
    "\14\3\2\0\2\3\24\0\14\3\1\136\5\3\2\0"+
    "\2\3\24\0\3\3\1\137\16\3\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2646];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\2\1\1\11\1\1\1\11\3\1\1\11"+
    "\1\1\7\11\16\1\1\0\10\11\16\1\1\0\46\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 166) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return INT;
          }
        case 43: break;
        case 2: 
          { return ERROR;
          }
        case 44: break;
        case 3: 
          { return ID;
          }
        case 45: break;
        case 4: 
          { /*Ignore*/
          }
        case 46: break;
        case 5: 
          { return DIV;
          }
        case 47: break;
        case 6: 
          { return MULT;
          }
        case 48: break;
        case 7: 
          { return LESS_THAN;
          }
        case 49: break;
        case 8: 
          { return GREATER_THAN;
          }
        case 50: break;
        case 9: 
          { return ASSIGN;
          }
        case 51: break;
        case 10: 
          { return MODULE;
          }
        case 52: break;
        case 11: 
          { return NOT;
          }
        case 53: break;
        case 12: 
          { return LPAR;
          }
        case 54: break;
        case 13: 
          { return RPAR;
          }
        case 55: break;
        case 14: 
          { return END_EXP;
          }
        case 56: break;
        case 15: 
          { return LC;
          }
        case 57: break;
        case 16: 
          { return RC;
          }
        case 58: break;
        case 17: 
          { return LLL;
          }
        case 59: break;
        case 18: 
          { return RLL;
          }
        case 60: break;
        case 19: 
          { return PLUS;
          }
        case 61: break;
        case 20: 
          { return MINUS;
          }
        case 62: break;
        case 21: 
          { return LESS_EQ_THAN;
          }
        case 63: break;
        case 22: 
          { return GREATER_EQ_THAN;
          }
        case 64: break;
        case 23: 
          { return EQ;
          }
        case 65: break;
        case 24: 
          { return NOT_EQ;
          }
        case 66: break;
        case 25: 
          { return OR;
          }
        case 67: break;
        case 26: 
          { return AND;
          }
        case 68: break;
        case 27: 
          { return ASSIGN_INC;
          }
        case 69: break;
        case 28: 
          { return ASSIGN_DEC;
          }
        case 70: break;
        case 29: 
          { return WIF;
          }
        case 71: break;
        case 30: 
          { return WINT;
          }
        case 72: break;
        case 31: 
          { return WFOR;
          }
        case 73: break;
        case 32: 
          { return WELSE;
          }
        case 74: break;
        case 33: 
          { return WTRUE;
          }
        case 75: break;
        case 34: 
          { return WVOID;
          }
        case 76: break;
        case 35: 
          { return WBREAK;
          }
        case 77: break;
        case 36: 
          { return WCLASS;
          }
        case 78: break;
        case 37: 
          { return WFLOAT;
          }
        case 79: break;
        case 38: 
          { return WFALSE;
          }
        case 80: break;
        case 39: 
          { return WWHILE;
          }
        case 81: break;
        case 40: 
          { return WRETURN;
          }
        case 82: break;
        case 41: 
          { return WBOOLEAN;
          }
        case 83: break;
        case 42: 
          { return WCONTINUE;
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
