
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 02 21:29:49 ART 2014
//----------------------------------------------------

package syntaxAnalyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 41;
  public static final int MULT = 25;
  public static final int GREATER_EQ_THAN = 23;
  public static final int ASSIGN_INC = 42;
  public static final int INT = 38;
  public static final int LESS_EQ_THAN = 22;
  public static final int WCONTINUE = 13;
  public static final int MINUS = 26;
  public static final int GREATER_THAN = 21;
  public static final int WBOOLEAN = 37;
  public static final int WCLASS = 12;
  public static final int NOT = 33;
  public static final int SEMICOLON = 9;
  public static final int AND = 28;
  public static final int RPAR = 3;
  public static final int OR = 27;
  public static final int COMMA = 8;
  public static final int WIF = 16;
  public static final int DIV = 32;
  public static final int PLUS = 24;
  public static final int ASSIGN = 44;
  public static final int ID = 10;
  public static final int BOOLEAN = 40;
  public static final int EOF = 0;
  public static final int LC = 4;
  public static final int WBREAK = 11;
  public static final int error = 1;
  public static final int RC = 5;
  public static final int LLL = 6;
  public static final int WEXTERNINVK = 19;
  public static final int EQ = 29;
  public static final int WWHILE = 18;
  public static final int MODULE = 31;
  public static final int WFLOAT = 36;
  public static final int ASSIGN_DEC = 43;
  public static final int WRETURN = 17;
  public static final int NOT_EQ = 30;
  public static final int FLOAT = 39;
  public static final int WVOID = 34;
  public static final int LPAR = 2;
  public static final int WELSE = 14;
  public static final int RLL = 7;
  public static final int WINT = 35;
  public static final int LESS_THAN = 20;
  public static final int WFOR = 15;
}

