
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 08 16:11:35 ART 2014
//----------------------------------------------------

package compiler2014;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 44;
  public static final int MULT = 31;
  public static final int GREATER_EQ_THAN = 16;
  public static final int INT = 41;
  public static final int LESS_EQ_THAN = 15;
  public static final int ASSIGN_INC = 27;
  public static final int WCONTINUE = 6;
  public static final int MINUS = 32;
  public static final int GREATER_THAN = 14;
  public static final int WCLASS = 4;
  public static final int WBOOLEAN = 2;
  public static final int SEMICOLON = 36;
  public static final int NOT = 19;
  public static final int AND = 26;
  public static final int RPAR = 21;
  public static final int OR = 25;
  public static final int COMMA = 35;
  public static final int WIF = 10;
  public static final int DIV = 38;
  public static final int PLUS = 30;
  public static final int ASSIGN = 29;
  public static final int ID = 39;
  public static final int BOOLEAN = 43;
  public static final int EOF = 0;
  public static final int LC = 22;
  public static final int WBREAK = 3;
  public static final int error = 1;
  public static final int RC = 23;
  public static final int LLL = 33;
  public static final int WEXTERNINVK = 37;
  public static final int EQ = 24;
  public static final int WWHILE = 12;
  public static final int MODULE = 18;
  public static final int WFLOAT = 8;
  public static final int WRETURN = 11;
  public static final int ASSIGN_DEC = 28;
  public static final int NOT_EQ = 17;
  public static final int FLOAT = 42;
  public static final int WVOID = 40;
  public static final int LPAR = 20;
  public static final int WELSE = 7;
  public static final int RLL = 34;
  public static final int WINT = 5;
  public static final int LESS_THAN = 13;
  public static final int WFOR = 9;
}

