
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 11 20:28:53 ART 2014
//----------------------------------------------------

package compiler2014;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 41;
  public static final int MULT = 29;
  public static final int GREATER_EQ_THAN = 27;
  public static final int ASSIGN_INC = 42;
  public static final int INT = 38;
  public static final int LESS_EQ_THAN = 26;
  public static final int WCONTINUE = 16;
  public static final int MINUS = 30;
  public static final int GREATER_THAN = 25;
  public static final int WCLASS = 14;
  public static final int WBOOLEAN = 12;
  public static final int NOT = 37;
  public static final int SEMICOLON = 9;
  public static final int AND = 32;
  public static final int RPAR = 3;
  public static final int OR = 31;
  public static final int COMMA = 8;
  public static final int WIF = 20;
  public static final int DIV = 36;
  public static final int PLUS = 28;
  public static final int ASSIGN = 44;
  public static final int ID = 10;
  public static final int BOOLEAN = 40;
  public static final int EOF = 0;
  public static final int LC = 4;
  public static final int WBREAK = 13;
  public static final int error = 1;
  public static final int RC = 5;
  public static final int LLL = 6;
  public static final int WEXTERNINVK = 23;
  public static final int EQ = 33;
  public static final int MODULE = 35;
  public static final int WWHILE = 22;
  public static final int WFLOAT = 18;
  public static final int ASSIGN_DEC = 43;
  public static final int WRETURN = 21;
  public static final int NOT_EQ = 34;
  public static final int FLOAT = 39;
  public static final int WVOID = 11;
  public static final int LPAR = 2;
  public static final int WELSE = 17;
  public static final int RLL = 7;
  public static final int WINT = 15;
  public static final int LESS_THAN = 24;
  public static final int WFOR = 19;
}

